Prepare kb
ostis-dev/ims.ostis.kb pull request #95
Opened 2021-03-29 09:23 UTC by Vikort

2021-03-30 16:54 UTC, KovalM commented on prepare_kb.py
> +        os.system("python3 " + os.path.join(kb_path, 'scripts', script) + ' ' + copy_path)
I think we will need to have ability to run scripts in a given order or not run some script. Simple way do support it is create list of scripts here and run each script from this list in turn

2021-04-01 23:50 UTC, KovalM approved these changes

2021-04-02 11:37 UTC, MikhailSadovsky requested changes

2021-04-02 11:37 UTC, MikhailSadovsky commented on scripts/remove_scsi.py
> +    if os.name == 'nt':
Please remove this if section as we're not supporting nt

2021-04-02 11:37 UTC, MikhailSadovsky commented on prepare_kb.py
> +    if os.path.isfile(script) and script != 'copy_kb.py' and script.endswith('.py'):
Looks like this condition isn't needed as `scripts` list created by hands

2021-04-02 11:37 UTC, MikhailSadovsky commented on scripts/remove_scsi.py
> +        print("invalid numb of arguments, Please specify only the work directory")
```suggestion
        print("invalid number of arguments, Please specify only the work directory")

```

2021-04-02 11:37 UTC, MikhailSadovsky commented on scripts/remove_scsi.py
> +            is_edit = False
```suggestion
            is_file_processed = False

```

2021-04-02 11:38 UTC, MikhailSadovsky commented
Please add the brief description of your changes in PR description

2021-04-05 11:09 UTC, MikhailSadovsky requested changes

2021-04-05 11:09 UTC, MikhailSadovsky commented on prepare_kb.py
> +    # if os.path.isfile(script) and script != 'copy_kb.py' and script.endswith('.py'):
```suggestion
```

2021-04-20 12:13 UTC, closed without merging

2021-04-20 12:40 UTC, MikhailSadovsky commented
Closing as a duplicate for #91